export const BOTTOM_MARGIN = 84
export const FAN_ARC_HEIGHT = 22
export const FAN_MAX_CARDS = 12
export const HOVER_LIFT = 24
export const HOVER_SCALE = 1.08
export const MAX_ROTATION = 7
export const MAX_SPACING = 120
export const MIN_SCALE = 1
export const MIN_SPACING = 22
export const SCROLL_GUTTER_WIDTH = 50
export const SCROLL_HOVER_DELAY_MS = 240
export const SCROLL_HOVER_INTERVAL_MS = 160
export const SCROLL_STEP = 20 // scroll speed
export const SIDE_MARGIN = 20
