// enemy
export const ARCHER = 'archer'
export const HATCHLING = 'hatchling'
export const REAVER = 'reaver'
export const SOLDIER = 'soldier'

// card
export const BASTION = 'bastion'
export const BLOOM = 'bloom'
export const BURN = 'burn'
export const CHARGE = 'charge'
export const DOUBLE = 'double'
export const ECHO = 'echo'
export const FOCUS = 'focus'
export const HEAT = 'heat'
export const HEAVY = 'heavy'
export const LEECH = 'leech'
export const PIERCE = 'pierce'
export const QUICK = 'quick'
export const RAGE = 'rage'
export const RISKY = 'risky'
export const SAFE = 'safe'
export const SEAR = 'sear'
export const SHIELD = 'shield'
export const SURGE = 'surge'
export const THORN = 'thorn'
export const WARD = 'ward'
export const WIDE = 'wide'
export const WILT = 'wilt'
